In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    if prediction[0][0] > 0.7 :
        print('Rock')
    elif prediction[0][1] > 0.7:
        print('Paper')
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Rock
[[9.8829830e-01 4.0570647e-03 7.6433416e-03 1.2319560e-06]]
1/1 [==============================] - 0s 40ms/step
Rock
[[8.71932685e-01 2.47435495e-02 1.03319936e-01 3.76195408e-06]]
1/1 [==============================] - 0s 34ms/step
Rock
[[9.2855412e-01 8.5135363e-03 6.2929422e-02 2.8630923e-06]]
1/1 [==============================] - 0s 39ms/step
Rock
[[9.7376740e-01 6.7151892e-03 1.9516297e-02 1.0647196e-06]]
1/1 [==============================] - 0s 42ms/step
Rock
[[9.7577763e-01 7.9835812e-03 1.6237227e-02 1.5528076e-06]]
1/1 [==============================] - 0s 34ms/step
Rock
[[9.6289122e-01 9.1310497e-03 2.7976550e-02 1.2260638e-06]]
1/1 [==============================] - 0s 35ms/step
Rock
[[9.6289122e-01 9.1310497e-03 2.7976550e-02 1.2260638e-06]]
1/1 [==============================] - 0s 30ms/step
Rock
[[9.7391719e-01 9.1468589e-03 1.6934089e-02 1.7680927e-06]]
1/1 [==============================] - 0s 33ms/step
Rock
[[8.50170732e-01 2.80492809e-02 1.21775396e-01 4.625638

KeyboardInterrupt: 

: 